<footer>
        <ul>Pour nous contacter :</ul>

		<ul>Siège Social : 52 B/8 rue du Beck </ul>
		<ul>59150 Wattrelos</ul>

        <div style="text-align: center; display: flex; justify-content: center; gap: 30px; flex-wrap: wrap;">

			<div style="text-align: center;">
			<a href="https://fr-fr.facebook.com/sftrugby/" target="_blank" rel="noopener">
				<img src="img/icons/facebook.png" alt="Facebook" style="width:40px; height:40px;">
			</a>
			<div>Facebook</div>
			</div>

			<div style="text-align: center;">
			<a href="https://www.instagram.com/solidarite59/?locale=fr_FR&hl=am-et" target="_blank" rel="noopener">
				<img src="img/icons/instagram.png" alt="Instagram" style="width:40px; height:40px;">
			</a>
			<div>Instagram</div>
			</div>

			<div style="text-align: center;">
			<a href="mailto:solidarite.frugby@yahoo.com">
				<img src="img/icons/yahoo.png" alt="Mail" style="width:40px; height:40px;">
			</a>
			<div>Mail</div>
			</div>

			<div style="text-align: center;">
			<img src="img/icons/phone.png" alt="Téléphone" style="width:40px; height:40px;">
			<div>0612829334</div>
		</div>
<style>
        div {
            color: white;
        }
		ul {
			color: white;
		}
    </div>
    </footer>
