<header>
    <title>Solidarité Fraternité "Tous pour le Rugby"</title>
    <h1 class="first-h1">Solidarité Fraternité</h1>
    <h1 class="second-h1">"Tous pour le Rugby"</h1>
    <img src="img/icons/logo.png" alt="Le logo de l'association"/>
	<link rel="icon" type="image/png" href="img/icons/logo.png">
    <nav>
        <ul class="navigation">
            <li><a href="index.php?action=solidarite_fraternite_tous_pour_le_rugby">Accueil</a></li>
            <li><a href="index.php?action=notre_assoc">Notre Association</a></li>
            <li><a href="index.php?action=actusrugby">Actualités</a></li>
            <li><a href="index.php?action=projet_sportif">Projet Sportif</a></li>
            <li><a href="index.php?action=images">Images</a></li>
        </ul>
    </nav>
    <style>
        h1 {
            position: absolute;
            color: white;
            text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.8);
            width: 100%;
            text-align: center;
        }
        .first-h1 {
            top: 30px; /* Positionnez le premier h1 */
        }

        .second-h1 {
            top: 100px; /* Positionnez le second h1 légèrement en dessous du premier */
        }
        img {
            width: 350px; 
            height: auto; 
            box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15);
        }
    </style>
</header>
